#!/bin/bash
export WATER="ewwwatratewa" | export STIR="ti.itirtrtr" | echo $(printf% $(($((5#$(echo $WATER | tr 'water' '01234'))))) + $((5#$(echo $STIR | tr 'stir.' '01234')))| tr '01234567' 'bestcholl')
